#!/bin/bash
festlearn -d 1 -n 0.1 -t 1 train-raw-ap.data train-raw-ap-bt-1.data.model &&
festlearn -d 1 -n 0.1 -t 2 train-raw-ap.data train-raw-ap-bt-2.data.model &&
festlearn -d 1 -n 0.1 -t 3 train-raw-ap.data train-raw-ap-bt-3.data.model &&
festlearn -d 1 -n 0.1 -t 4 train-raw-ap.data train-raw-ap-bt-4.data.model &&
festlearn -d 1 -n 0.1 -t 5 train-raw-ap.data train-raw-ap-bt-5.data.model &&
festlearn -d 1 -n 0.1 -t 6 train-raw-ap.data train-raw-ap-bt-6.data.model &&
festlearn -d 1 -n 0.1 -t 7 train-raw-ap.data train-raw-ap-bt-7.data.model &&
festlearn -d 1 -n 0.1 -t 8 train-raw-ap.data train-raw-ap-bt-8.data.model &&
festlearn -d 1 -n 0.1 -t 9 train-raw-ap.data train-raw-ap-bt-9.data.model &&
festlearn -d 1 -n 0.1 -t 10 train-raw-ap.data train-raw-ap-bt-10.data.model &&
festlearn -d 1 -n 0.1 -t 11 train-raw-ap.data train-raw-ap-bt-11.data.model &&
festlearn -d 1 -n 0.1 -t 12 train-raw-ap.data train-raw-ap-bt-12.data.model &&
festlearn -d 1 -n 0.1 -t 13 train-raw-ap.data train-raw-ap-bt-13.data.model &&
festlearn -d 1 -n 0.1 -t 14 train-raw-ap.data train-raw-ap-bt-14.data.model &&
festlearn -d 1 -n 0.1 -t 15 train-raw-ap.data train-raw-ap-bt-15.data.model &&
festlearn -d 1 -n 0.1 -t 16 train-raw-ap.data train-raw-ap-bt-16.data.model &&
festlearn -d 1 -n 0.1 -t 17 train-raw-ap.data train-raw-ap-bt-17.data.model &&
festlearn -d 1 -n 0.1 -t 18 train-raw-ap.data train-raw-ap-bt-18.data.model &&
festlearn -d 1 -n 0.1 -t 19 train-raw-ap.data train-raw-ap-bt-19.data.model &&
festlearn -d 1 -n 0.1 -t 20 train-raw-ap.data train-raw-ap-bt-20.data.model &&
festlearn -d 1 -n 0.1 -t 21 train-raw-ap.data train-raw-ap-bt-21.data.model &&
festlearn -d 1 -n 0.1 -t 22 train-raw-ap.data train-raw-ap-bt-22.data.model &&
festlearn -d 1 -n 0.1 -t 23 train-raw-ap.data train-raw-ap-bt-23.data.model &&
festlearn -d 1 -n 0.1 -t 24 train-raw-ap.data train-raw-ap-bt-24.data.model &&
festlearn -d 1 -n 0.1 -t 25 train-raw-ap.data train-raw-ap-bt-25.data.model &&
festlearn -d 1 -n 0.1 -t 26 train-raw-ap.data train-raw-ap-bt-26.data.model &&
festlearn -d 1 -n 0.1 -t 27 train-raw-ap.data train-raw-ap-bt-27.data.model &&
festlearn -d 1 -n 0.1 -t 28 train-raw-ap.data train-raw-ap-bt-28.data.model &&
festlearn -d 1 -n 0.1 -t 29 train-raw-ap.data train-raw-ap-bt-29.data.model &&
festlearn -d 1 -n 0.1 -t 30 train-raw-ap.data train-raw-ap-bt-30.data.model &&
festlearn -d 1 -n 0.1 -t 31 train-raw-ap.data train-raw-ap-bt-31.data.model &&
festlearn -d 1 -n 0.1 -t 32 train-raw-ap.data train-raw-ap-bt-32.data.model &&
festlearn -d 1 -n 0.1 -t 33 train-raw-ap.data train-raw-ap-bt-33.data.model &&
festlearn -d 1 -n 0.1 -t 34 train-raw-ap.data train-raw-ap-bt-34.data.model &&
festlearn -d 1 -n 0.1 -t 35 train-raw-ap.data train-raw-ap-bt-35.data.model &&
festlearn -d 1 -n 0.1 -t 36 train-raw-ap.data train-raw-ap-bt-36.data.model &&
festlearn -d 1 -n 0.1 -t 37 train-raw-ap.data train-raw-ap-bt-37.data.model &&
festlearn -d 1 -n 0.1 -t 38 train-raw-ap.data train-raw-ap-bt-38.data.model &&
festlearn -d 1 -n 0.1 -t 39 train-raw-ap.data train-raw-ap-bt-39.data.model &&
festlearn -d 1 -n 0.1 -t 40 train-raw-ap.data train-raw-ap-bt-40.data.model &&
festlearn -d 1 -n 0.1 -t 41 train-raw-ap.data train-raw-ap-bt-41.data.model &&
festlearn -d 1 -n 0.1 -t 42 train-raw-ap.data train-raw-ap-bt-42.data.model &&
festlearn -d 1 -n 0.1 -t 43 train-raw-ap.data train-raw-ap-bt-43.data.model &&
festlearn -d 1 -n 0.1 -t 44 train-raw-ap.data train-raw-ap-bt-44.data.model &&
festlearn -d 1 -n 0.1 -t 45 train-raw-ap.data train-raw-ap-bt-45.data.model &&
festlearn -d 1 -n 0.1 -t 46 train-raw-ap.data train-raw-ap-bt-46.data.model &&
festlearn -d 1 -n 0.1 -t 47 train-raw-ap.data train-raw-ap-bt-47.data.model &&
festlearn -d 1 -n 0.1 -t 48 train-raw-ap.data train-raw-ap-bt-48.data.model &&
festlearn -d 1 -n 0.1 -t 49 train-raw-ap.data train-raw-ap-bt-49.data.model &&
festlearn -d 1 -n 0.1 -t 50 train-raw-ap.data train-raw-ap-bt-50.data.model &&
festlearn -d 1 -n 0.1 -t 51 train-raw-ap.data train-raw-ap-bt-51.data.model &&
festlearn -d 1 -n 0.1 -t 52 train-raw-ap.data train-raw-ap-bt-52.data.model &&
festlearn -d 1 -n 0.1 -t 53 train-raw-ap.data train-raw-ap-bt-53.data.model &&
festlearn -d 1 -n 0.1 -t 54 train-raw-ap.data train-raw-ap-bt-54.data.model &&
festlearn -d 1 -n 0.1 -t 55 train-raw-ap.data train-raw-ap-bt-55.data.model &&
festlearn -d 1 -n 0.1 -t 56 train-raw-ap.data train-raw-ap-bt-56.data.model &&
festlearn -d 1 -n 0.1 -t 57 train-raw-ap.data train-raw-ap-bt-57.data.model &&
festlearn -d 1 -n 0.1 -t 58 train-raw-ap.data train-raw-ap-bt-58.data.model &&
festlearn -d 1 -n 0.1 -t 59 train-raw-ap.data train-raw-ap-bt-59.data.model &&
festlearn -d 1 -n 0.1 -t 60 train-raw-ap.data train-raw-ap-bt-60.data.model &&
festlearn -d 1 -n 0.1 -t 61 train-raw-ap.data train-raw-ap-bt-61.data.model &&
festlearn -d 1 -n 0.1 -t 62 train-raw-ap.data train-raw-ap-bt-62.data.model &&
festlearn -d 1 -n 0.1 -t 63 train-raw-ap.data train-raw-ap-bt-63.data.model &&
festlearn -d 1 -n 0.1 -t 64 train-raw-ap.data train-raw-ap-bt-64.data.model &&
festlearn -d 1 -n 0.1 -t 65 train-raw-ap.data train-raw-ap-bt-65.data.model &&
festlearn -d 1 -n 0.1 -t 66 train-raw-ap.data train-raw-ap-bt-66.data.model &&
festlearn -d 1 -n 0.1 -t 67 train-raw-ap.data train-raw-ap-bt-67.data.model &&
festlearn -d 1 -n 0.1 -t 68 train-raw-ap.data train-raw-ap-bt-68.data.model &&
festlearn -d 1 -n 0.1 -t 69 train-raw-ap.data train-raw-ap-bt-69.data.model &&
festlearn -d 1 -n 0.1 -t 70 train-raw-ap.data train-raw-ap-bt-70.data.model &&
festlearn -d 1 -n 0.1 -t 71 train-raw-ap.data train-raw-ap-bt-71.data.model &&
festlearn -d 1 -n 0.1 -t 72 train-raw-ap.data train-raw-ap-bt-72.data.model &&
festlearn -d 1 -n 0.1 -t 73 train-raw-ap.data train-raw-ap-bt-73.data.model &&
festlearn -d 1 -n 0.1 -t 74 train-raw-ap.data train-raw-ap-bt-74.data.model &&
festlearn -d 1 -n 0.1 -t 75 train-raw-ap.data train-raw-ap-bt-75.data.model &&
festlearn -d 1 -n 0.1 -t 76 train-raw-ap.data train-raw-ap-bt-76.data.model &&
festlearn -d 1 -n 0.1 -t 77 train-raw-ap.data train-raw-ap-bt-77.data.model &&
festlearn -d 1 -n 0.1 -t 78 train-raw-ap.data train-raw-ap-bt-78.data.model &&
festlearn -d 1 -n 0.1 -t 79 train-raw-ap.data train-raw-ap-bt-79.data.model &&
festlearn -d 1 -n 0.1 -t 80 train-raw-ap.data train-raw-ap-bt-80.data.model &&
festlearn -d 1 -n 0.1 -t 81 train-raw-ap.data train-raw-ap-bt-81.data.model &&
festlearn -d 1 -n 0.1 -t 82 train-raw-ap.data train-raw-ap-bt-82.data.model &&
festlearn -d 1 -n 0.1 -t 83 train-raw-ap.data train-raw-ap-bt-83.data.model &&
festlearn -d 1 -n 0.1 -t 84 train-raw-ap.data train-raw-ap-bt-84.data.model &&
festlearn -d 1 -n 0.1 -t 85 train-raw-ap.data train-raw-ap-bt-85.data.model &&
festlearn -d 1 -n 0.1 -t 86 train-raw-ap.data train-raw-ap-bt-86.data.model &&
festlearn -d 1 -n 0.1 -t 87 train-raw-ap.data train-raw-ap-bt-87.data.model &&
festlearn -d 1 -n 0.1 -t 88 train-raw-ap.data train-raw-ap-bt-88.data.model &&
festlearn -d 1 -n 0.1 -t 89 train-raw-ap.data train-raw-ap-bt-89.data.model &&
festlearn -d 1 -n 0.1 -t 90 train-raw-ap.data train-raw-ap-bt-90.data.model &&
festlearn -d 1 -n 0.1 -t 91 train-raw-ap.data train-raw-ap-bt-91.data.model &&
festlearn -d 1 -n 0.1 -t 92 train-raw-ap.data train-raw-ap-bt-92.data.model &&
festlearn -d 1 -n 0.1 -t 93 train-raw-ap.data train-raw-ap-bt-93.data.model &&
festlearn -d 1 -n 0.1 -t 94 train-raw-ap.data train-raw-ap-bt-94.data.model &&
festlearn -d 1 -n 0.1 -t 95 train-raw-ap.data train-raw-ap-bt-95.data.model &&
festlearn -d 1 -n 0.1 -t 96 train-raw-ap.data train-raw-ap-bt-96.data.model &&
festlearn -d 1 -n 0.1 -t 97 train-raw-ap.data train-raw-ap-bt-97.data.model &&
festlearn -d 1 -n 0.1 -t 98 train-raw-ap.data train-raw-ap-bt-98.data.model &&
festlearn -d 1 -n 0.1 -t 99 train-raw-ap.data train-raw-ap-bt-99.data.model &&
festlearn -d 1 -n 0.1 -t 100 train-raw-ap.data train-raw-ap-bt-100.data.model &&
festlearn -d 1 -n 0.1 -t 101 train-raw-ap.data train-raw-ap-bt-101.data.model &&
festlearn -d 1 -n 0.1 -t 102 train-raw-ap.data train-raw-ap-bt-102.data.model &&
festlearn -d 1 -n 0.1 -t 103 train-raw-ap.data train-raw-ap-bt-103.data.model &&
festlearn -d 1 -n 0.1 -t 104 train-raw-ap.data train-raw-ap-bt-104.data.model &&
festlearn -d 1 -n 0.1 -t 105 train-raw-ap.data train-raw-ap-bt-105.data.model &&
festlearn -d 1 -n 0.1 -t 106 train-raw-ap.data train-raw-ap-bt-106.data.model &&
festlearn -d 1 -n 0.1 -t 107 train-raw-ap.data train-raw-ap-bt-107.data.model &&
festlearn -d 1 -n 0.1 -t 108 train-raw-ap.data train-raw-ap-bt-108.data.model &&
festlearn -d 1 -n 0.1 -t 109 train-raw-ap.data train-raw-ap-bt-109.data.model &&
festlearn -d 1 -n 0.1 -t 110 train-raw-ap.data train-raw-ap-bt-110.data.model &&
festlearn -d 1 -n 0.1 -t 111 train-raw-ap.data train-raw-ap-bt-111.data.model &&
festlearn -d 1 -n 0.1 -t 112 train-raw-ap.data train-raw-ap-bt-112.data.model &&
festlearn -d 1 -n 0.1 -t 113 train-raw-ap.data train-raw-ap-bt-113.data.model &&
festlearn -d 1 -n 0.1 -t 114 train-raw-ap.data train-raw-ap-bt-114.data.model &&
festlearn -d 1 -n 0.1 -t 115 train-raw-ap.data train-raw-ap-bt-115.data.model &&
festlearn -d 1 -n 0.1 -t 116 train-raw-ap.data train-raw-ap-bt-116.data.model &&
festlearn -d 1 -n 0.1 -t 117 train-raw-ap.data train-raw-ap-bt-117.data.model &&
festlearn -d 1 -n 0.1 -t 118 train-raw-ap.data train-raw-ap-bt-118.data.model &&
festlearn -d 1 -n 0.1 -t 119 train-raw-ap.data train-raw-ap-bt-119.data.model &&
festlearn -d 1 -n 0.1 -t 120 train-raw-ap.data train-raw-ap-bt-120.data.model &&
festlearn -d 1 -n 0.1 -t 121 train-raw-ap.data train-raw-ap-bt-121.data.model &&
festlearn -d 1 -n 0.1 -t 122 train-raw-ap.data train-raw-ap-bt-122.data.model &&
festlearn -d 1 -n 0.1 -t 123 train-raw-ap.data train-raw-ap-bt-123.data.model &&
festlearn -d 1 -n 0.1 -t 124 train-raw-ap.data train-raw-ap-bt-124.data.model &&
festlearn -d 1 -n 0.1 -t 125 train-raw-ap.data train-raw-ap-bt-125.data.model &&
festlearn -d 1 -n 0.1 -t 126 train-raw-ap.data train-raw-ap-bt-126.data.model &&
festlearn -d 1 -n 0.1 -t 127 train-raw-ap.data train-raw-ap-bt-127.data.model &&
festlearn -d 1 -n 0.1 -t 128 train-raw-ap.data train-raw-ap-bt-128.data.model

# Life is never easy. Dude.
festlearn -d 1 -n 0.1 -t 1 train-raw-ch.data train-raw-ch-bt-1.data.model &&
festlearn -d 1 -n 0.1 -t 2 train-raw-ch.data train-raw-ch-bt-2.data.model &&
festlearn -d 1 -n 0.1 -t 3 train-raw-ch.data train-raw-ch-bt-3.data.model &&
festlearn -d 1 -n 0.1 -t 4 train-raw-ch.data train-raw-ch-bt-4.data.model &&
festlearn -d 1 -n 0.1 -t 5 train-raw-ch.data train-raw-ch-bt-5.data.model &&
festlearn -d 1 -n 0.1 -t 6 train-raw-ch.data train-raw-ch-bt-6.data.model &&
festlearn -d 1 -n 0.1 -t 7 train-raw-ch.data train-raw-ch-bt-7.data.model &&
festlearn -d 1 -n 0.1 -t 8 train-raw-ch.data train-raw-ch-bt-8.data.model &&
festlearn -d 1 -n 0.1 -t 9 train-raw-ch.data train-raw-ch-bt-9.data.model &&
festlearn -d 1 -n 0.1 -t 10 train-raw-ch.data train-raw-ch-bt-10.data.model &&
festlearn -d 1 -n 0.1 -t 11 train-raw-ch.data train-raw-ch-bt-11.data.model &&
festlearn -d 1 -n 0.1 -t 12 train-raw-ch.data train-raw-ch-bt-12.data.model &&
festlearn -d 1 -n 0.1 -t 13 train-raw-ch.data train-raw-ch-bt-13.data.model &&
festlearn -d 1 -n 0.1 -t 14 train-raw-ch.data train-raw-ch-bt-14.data.model &&
festlearn -d 1 -n 0.1 -t 15 train-raw-ch.data train-raw-ch-bt-15.data.model &&
festlearn -d 1 -n 0.1 -t 16 train-raw-ch.data train-raw-ch-bt-16.data.model &&
festlearn -d 1 -n 0.1 -t 17 train-raw-ch.data train-raw-ch-bt-17.data.model &&
festlearn -d 1 -n 0.1 -t 18 train-raw-ch.data train-raw-ch-bt-18.data.model &&
festlearn -d 1 -n 0.1 -t 19 train-raw-ch.data train-raw-ch-bt-19.data.model &&
festlearn -d 1 -n 0.1 -t 20 train-raw-ch.data train-raw-ch-bt-20.data.model &&
festlearn -d 1 -n 0.1 -t 21 train-raw-ch.data train-raw-ch-bt-21.data.model &&
festlearn -d 1 -n 0.1 -t 22 train-raw-ch.data train-raw-ch-bt-22.data.model &&
festlearn -d 1 -n 0.1 -t 23 train-raw-ch.data train-raw-ch-bt-23.data.model &&
festlearn -d 1 -n 0.1 -t 24 train-raw-ch.data train-raw-ch-bt-24.data.model &&
festlearn -d 1 -n 0.1 -t 25 train-raw-ch.data train-raw-ch-bt-25.data.model &&
festlearn -d 1 -n 0.1 -t 26 train-raw-ch.data train-raw-ch-bt-26.data.model &&
festlearn -d 1 -n 0.1 -t 27 train-raw-ch.data train-raw-ch-bt-27.data.model &&
festlearn -d 1 -n 0.1 -t 28 train-raw-ch.data train-raw-ch-bt-28.data.model &&
festlearn -d 1 -n 0.1 -t 29 train-raw-ch.data train-raw-ch-bt-29.data.model &&
festlearn -d 1 -n 0.1 -t 30 train-raw-ch.data train-raw-ch-bt-30.data.model &&
festlearn -d 1 -n 0.1 -t 31 train-raw-ch.data train-raw-ch-bt-31.data.model &&
festlearn -d 1 -n 0.1 -t 32 train-raw-ch.data train-raw-ch-bt-32.data.model &&
festlearn -d 1 -n 0.1 -t 33 train-raw-ch.data train-raw-ch-bt-33.data.model &&
festlearn -d 1 -n 0.1 -t 34 train-raw-ch.data train-raw-ch-bt-34.data.model &&
festlearn -d 1 -n 0.1 -t 35 train-raw-ch.data train-raw-ch-bt-35.data.model &&
festlearn -d 1 -n 0.1 -t 36 train-raw-ch.data train-raw-ch-bt-36.data.model &&
festlearn -d 1 -n 0.1 -t 37 train-raw-ch.data train-raw-ch-bt-37.data.model &&
festlearn -d 1 -n 0.1 -t 38 train-raw-ch.data train-raw-ch-bt-38.data.model &&
festlearn -d 1 -n 0.1 -t 39 train-raw-ch.data train-raw-ch-bt-39.data.model &&
festlearn -d 1 -n 0.1 -t 40 train-raw-ch.data train-raw-ch-bt-40.data.model &&
festlearn -d 1 -n 0.1 -t 41 train-raw-ch.data train-raw-ch-bt-41.data.model &&
festlearn -d 1 -n 0.1 -t 42 train-raw-ch.data train-raw-ch-bt-42.data.model &&
festlearn -d 1 -n 0.1 -t 43 train-raw-ch.data train-raw-ch-bt-43.data.model &&
festlearn -d 1 -n 0.1 -t 44 train-raw-ch.data train-raw-ch-bt-44.data.model &&
festlearn -d 1 -n 0.1 -t 45 train-raw-ch.data train-raw-ch-bt-45.data.model &&
festlearn -d 1 -n 0.1 -t 46 train-raw-ch.data train-raw-ch-bt-46.data.model &&
festlearn -d 1 -n 0.1 -t 47 train-raw-ch.data train-raw-ch-bt-47.data.model &&
festlearn -d 1 -n 0.1 -t 48 train-raw-ch.data train-raw-ch-bt-48.data.model &&
festlearn -d 1 -n 0.1 -t 49 train-raw-ch.data train-raw-ch-bt-49.data.model &&
festlearn -d 1 -n 0.1 -t 50 train-raw-ch.data train-raw-ch-bt-50.data.model &&
festlearn -d 1 -n 0.1 -t 51 train-raw-ch.data train-raw-ch-bt-51.data.model &&
festlearn -d 1 -n 0.1 -t 52 train-raw-ch.data train-raw-ch-bt-52.data.model &&
festlearn -d 1 -n 0.1 -t 53 train-raw-ch.data train-raw-ch-bt-53.data.model &&
festlearn -d 1 -n 0.1 -t 54 train-raw-ch.data train-raw-ch-bt-54.data.model &&
festlearn -d 1 -n 0.1 -t 55 train-raw-ch.data train-raw-ch-bt-55.data.model &&
festlearn -d 1 -n 0.1 -t 56 train-raw-ch.data train-raw-ch-bt-56.data.model &&
festlearn -d 1 -n 0.1 -t 57 train-raw-ch.data train-raw-ch-bt-57.data.model &&
festlearn -d 1 -n 0.1 -t 58 train-raw-ch.data train-raw-ch-bt-58.data.model &&
festlearn -d 1 -n 0.1 -t 59 train-raw-ch.data train-raw-ch-bt-59.data.model &&
festlearn -d 1 -n 0.1 -t 60 train-raw-ch.data train-raw-ch-bt-60.data.model &&
festlearn -d 1 -n 0.1 -t 61 train-raw-ch.data train-raw-ch-bt-61.data.model &&
festlearn -d 1 -n 0.1 -t 62 train-raw-ch.data train-raw-ch-bt-62.data.model &&
festlearn -d 1 -n 0.1 -t 63 train-raw-ch.data train-raw-ch-bt-63.data.model &&
festlearn -d 1 -n 0.1 -t 64 train-raw-ch.data train-raw-ch-bt-64.data.model &&
festlearn -d 1 -n 0.1 -t 65 train-raw-ch.data train-raw-ch-bt-65.data.model &&
festlearn -d 1 -n 0.1 -t 66 train-raw-ch.data train-raw-ch-bt-66.data.model &&
festlearn -d 1 -n 0.1 -t 67 train-raw-ch.data train-raw-ch-bt-67.data.model &&
festlearn -d 1 -n 0.1 -t 68 train-raw-ch.data train-raw-ch-bt-68.data.model &&
festlearn -d 1 -n 0.1 -t 69 train-raw-ch.data train-raw-ch-bt-69.data.model &&
festlearn -d 1 -n 0.1 -t 70 train-raw-ch.data train-raw-ch-bt-70.data.model &&
festlearn -d 1 -n 0.1 -t 71 train-raw-ch.data train-raw-ch-bt-71.data.model &&
festlearn -d 1 -n 0.1 -t 72 train-raw-ch.data train-raw-ch-bt-72.data.model &&
festlearn -d 1 -n 0.1 -t 73 train-raw-ch.data train-raw-ch-bt-73.data.model &&
festlearn -d 1 -n 0.1 -t 74 train-raw-ch.data train-raw-ch-bt-74.data.model &&
festlearn -d 1 -n 0.1 -t 75 train-raw-ch.data train-raw-ch-bt-75.data.model &&
festlearn -d 1 -n 0.1 -t 76 train-raw-ch.data train-raw-ch-bt-76.data.model &&
festlearn -d 1 -n 0.1 -t 77 train-raw-ch.data train-raw-ch-bt-77.data.model &&
festlearn -d 1 -n 0.1 -t 78 train-raw-ch.data train-raw-ch-bt-78.data.model &&
festlearn -d 1 -n 0.1 -t 79 train-raw-ch.data train-raw-ch-bt-79.data.model &&
festlearn -d 1 -n 0.1 -t 80 train-raw-ch.data train-raw-ch-bt-80.data.model &&
festlearn -d 1 -n 0.1 -t 81 train-raw-ch.data train-raw-ch-bt-81.data.model &&
festlearn -d 1 -n 0.1 -t 82 train-raw-ch.data train-raw-ch-bt-82.data.model &&
festlearn -d 1 -n 0.1 -t 83 train-raw-ch.data train-raw-ch-bt-83.data.model &&
festlearn -d 1 -n 0.1 -t 84 train-raw-ch.data train-raw-ch-bt-84.data.model &&
festlearn -d 1 -n 0.1 -t 85 train-raw-ch.data train-raw-ch-bt-85.data.model &&
festlearn -d 1 -n 0.1 -t 86 train-raw-ch.data train-raw-ch-bt-86.data.model &&
festlearn -d 1 -n 0.1 -t 87 train-raw-ch.data train-raw-ch-bt-87.data.model &&
festlearn -d 1 -n 0.1 -t 88 train-raw-ch.data train-raw-ch-bt-88.data.model &&
festlearn -d 1 -n 0.1 -t 89 train-raw-ch.data train-raw-ch-bt-89.data.model &&
festlearn -d 1 -n 0.1 -t 90 train-raw-ch.data train-raw-ch-bt-90.data.model &&
festlearn -d 1 -n 0.1 -t 91 train-raw-ch.data train-raw-ch-bt-91.data.model &&
festlearn -d 1 -n 0.1 -t 92 train-raw-ch.data train-raw-ch-bt-92.data.model &&
festlearn -d 1 -n 0.1 -t 93 train-raw-ch.data train-raw-ch-bt-93.data.model &&
festlearn -d 1 -n 0.1 -t 94 train-raw-ch.data train-raw-ch-bt-94.data.model &&
festlearn -d 1 -n 0.1 -t 95 train-raw-ch.data train-raw-ch-bt-95.data.model &&
festlearn -d 1 -n 0.1 -t 96 train-raw-ch.data train-raw-ch-bt-96.data.model &&
festlearn -d 1 -n 0.1 -t 97 train-raw-ch.data train-raw-ch-bt-97.data.model &&
festlearn -d 1 -n 0.1 -t 98 train-raw-ch.data train-raw-ch-bt-98.data.model &&
festlearn -d 1 -n 0.1 -t 99 train-raw-ch.data train-raw-ch-bt-99.data.model &&
festlearn -d 1 -n 0.1 -t 100 train-raw-ch.data train-raw-ch-bt-100.data.model &&
festlearn -d 1 -n 0.1 -t 101 train-raw-ch.data train-raw-ch-bt-101.data.model &&
festlearn -d 1 -n 0.1 -t 102 train-raw-ch.data train-raw-ch-bt-102.data.model &&
festlearn -d 1 -n 0.1 -t 103 train-raw-ch.data train-raw-ch-bt-103.data.model &&
festlearn -d 1 -n 0.1 -t 104 train-raw-ch.data train-raw-ch-bt-104.data.model &&
festlearn -d 1 -n 0.1 -t 105 train-raw-ch.data train-raw-ch-bt-105.data.model &&
festlearn -d 1 -n 0.1 -t 106 train-raw-ch.data train-raw-ch-bt-106.data.model &&
festlearn -d 1 -n 0.1 -t 107 train-raw-ch.data train-raw-ch-bt-107.data.model &&
festlearn -d 1 -n 0.1 -t 108 train-raw-ch.data train-raw-ch-bt-108.data.model &&
festlearn -d 1 -n 0.1 -t 109 train-raw-ch.data train-raw-ch-bt-109.data.model &&
festlearn -d 1 -n 0.1 -t 110 train-raw-ch.data train-raw-ch-bt-110.data.model &&
festlearn -d 1 -n 0.1 -t 111 train-raw-ch.data train-raw-ch-bt-111.data.model &&
festlearn -d 1 -n 0.1 -t 112 train-raw-ch.data train-raw-ch-bt-112.data.model &&
festlearn -d 1 -n 0.1 -t 113 train-raw-ch.data train-raw-ch-bt-113.data.model &&
festlearn -d 1 -n 0.1 -t 114 train-raw-ch.data train-raw-ch-bt-114.data.model &&
festlearn -d 1 -n 0.1 -t 115 train-raw-ch.data train-raw-ch-bt-115.data.model &&
festlearn -d 1 -n 0.1 -t 116 train-raw-ch.data train-raw-ch-bt-116.data.model &&
festlearn -d 1 -n 0.1 -t 117 train-raw-ch.data train-raw-ch-bt-117.data.model &&
festlearn -d 1 -n 0.1 -t 118 train-raw-ch.data train-raw-ch-bt-118.data.model &&
festlearn -d 1 -n 0.1 -t 119 train-raw-ch.data train-raw-ch-bt-119.data.model &&
festlearn -d 1 -n 0.1 -t 120 train-raw-ch.data train-raw-ch-bt-120.data.model &&
festlearn -d 1 -n 0.1 -t 121 train-raw-ch.data train-raw-ch-bt-121.data.model &&
festlearn -d 1 -n 0.1 -t 122 train-raw-ch.data train-raw-ch-bt-122.data.model &&
festlearn -d 1 -n 0.1 -t 123 train-raw-ch.data train-raw-ch-bt-123.data.model &&
festlearn -d 1 -n 0.1 -t 124 train-raw-ch.data train-raw-ch-bt-124.data.model &&
festlearn -d 1 -n 0.1 -t 125 train-raw-ch.data train-raw-ch-bt-125.data.model &&
festlearn -d 1 -n 0.1 -t 126 train-raw-ch.data train-raw-ch-bt-126.data.model &&
festlearn -d 1 -n 0.1 -t 127 train-raw-ch.data train-raw-ch-bt-127.data.model &&
festlearn -d 1 -n 0.1 -t 128 train-raw-ch.data train-raw-ch-bt-128.data.model

# Masdar is an research institute.
festlearn -d 1 -n 0.1 -t 1 train-raw-up.data train-raw-up-bt-1.data.model &&
festlearn -d 1 -n 0.1 -t 2 train-raw-up.data train-raw-up-bt-2.data.model &&
festlearn -d 1 -n 0.1 -t 3 train-raw-up.data train-raw-up-bt-3.data.model &&
festlearn -d 1 -n 0.1 -t 4 train-raw-up.data train-raw-up-bt-4.data.model &&
festlearn -d 1 -n 0.1 -t 5 train-raw-up.data train-raw-up-bt-5.data.model &&
festlearn -d 1 -n 0.1 -t 6 train-raw-up.data train-raw-up-bt-6.data.model &&
festlearn -d 1 -n 0.1 -t 7 train-raw-up.data train-raw-up-bt-7.data.model &&
festlearn -d 1 -n 0.1 -t 8 train-raw-up.data train-raw-up-bt-8.data.model &&
festlearn -d 1 -n 0.1 -t 9 train-raw-up.data train-raw-up-bt-9.data.model &&
festlearn -d 1 -n 0.1 -t 10 train-raw-up.data train-raw-up-bt-10.data.model &&
festlearn -d 1 -n 0.1 -t 11 train-raw-up.data train-raw-up-bt-11.data.model &&
festlearn -d 1 -n 0.1 -t 12 train-raw-up.data train-raw-up-bt-12.data.model &&
festlearn -d 1 -n 0.1 -t 13 train-raw-up.data train-raw-up-bt-13.data.model &&
festlearn -d 1 -n 0.1 -t 14 train-raw-up.data train-raw-up-bt-14.data.model &&
festlearn -d 1 -n 0.1 -t 15 train-raw-up.data train-raw-up-bt-15.data.model &&
festlearn -d 1 -n 0.1 -t 16 train-raw-up.data train-raw-up-bt-16.data.model &&
festlearn -d 1 -n 0.1 -t 17 train-raw-up.data train-raw-up-bt-17.data.model &&
festlearn -d 1 -n 0.1 -t 18 train-raw-up.data train-raw-up-bt-18.data.model &&
festlearn -d 1 -n 0.1 -t 19 train-raw-up.data train-raw-up-bt-19.data.model &&
festlearn -d 1 -n 0.1 -t 20 train-raw-up.data train-raw-up-bt-20.data.model &&
festlearn -d 1 -n 0.1 -t 21 train-raw-up.data train-raw-up-bt-21.data.model &&
festlearn -d 1 -n 0.1 -t 22 train-raw-up.data train-raw-up-bt-22.data.model &&
festlearn -d 1 -n 0.1 -t 23 train-raw-up.data train-raw-up-bt-23.data.model &&
festlearn -d 1 -n 0.1 -t 24 train-raw-up.data train-raw-up-bt-24.data.model &&
festlearn -d 1 -n 0.1 -t 25 train-raw-up.data train-raw-up-bt-25.data.model &&
festlearn -d 1 -n 0.1 -t 26 train-raw-up.data train-raw-up-bt-26.data.model &&
festlearn -d 1 -n 0.1 -t 27 train-raw-up.data train-raw-up-bt-27.data.model &&
festlearn -d 1 -n 0.1 -t 28 train-raw-up.data train-raw-up-bt-28.data.model &&
festlearn -d 1 -n 0.1 -t 29 train-raw-up.data train-raw-up-bt-29.data.model &&
festlearn -d 1 -n 0.1 -t 30 train-raw-up.data train-raw-up-bt-30.data.model &&
festlearn -d 1 -n 0.1 -t 31 train-raw-up.data train-raw-up-bt-31.data.model &&
festlearn -d 1 -n 0.1 -t 32 train-raw-up.data train-raw-up-bt-32.data.model &&
festlearn -d 1 -n 0.1 -t 33 train-raw-up.data train-raw-up-bt-33.data.model &&
festlearn -d 1 -n 0.1 -t 34 train-raw-up.data train-raw-up-bt-34.data.model &&
festlearn -d 1 -n 0.1 -t 35 train-raw-up.data train-raw-up-bt-35.data.model &&
festlearn -d 1 -n 0.1 -t 36 train-raw-up.data train-raw-up-bt-36.data.model &&
festlearn -d 1 -n 0.1 -t 37 train-raw-up.data train-raw-up-bt-37.data.model &&
festlearn -d 1 -n 0.1 -t 38 train-raw-up.data train-raw-up-bt-38.data.model &&
festlearn -d 1 -n 0.1 -t 39 train-raw-up.data train-raw-up-bt-39.data.model &&
festlearn -d 1 -n 0.1 -t 40 train-raw-up.data train-raw-up-bt-40.data.model &&
festlearn -d 1 -n 0.1 -t 41 train-raw-up.data train-raw-up-bt-41.data.model &&
festlearn -d 1 -n 0.1 -t 42 train-raw-up.data train-raw-up-bt-42.data.model &&
festlearn -d 1 -n 0.1 -t 43 train-raw-up.data train-raw-up-bt-43.data.model &&
festlearn -d 1 -n 0.1 -t 44 train-raw-up.data train-raw-up-bt-44.data.model &&
festlearn -d 1 -n 0.1 -t 45 train-raw-up.data train-raw-up-bt-45.data.model &&
festlearn -d 1 -n 0.1 -t 46 train-raw-up.data train-raw-up-bt-46.data.model &&
festlearn -d 1 -n 0.1 -t 47 train-raw-up.data train-raw-up-bt-47.data.model &&
festlearn -d 1 -n 0.1 -t 48 train-raw-up.data train-raw-up-bt-48.data.model &&
festlearn -d 1 -n 0.1 -t 49 train-raw-up.data train-raw-up-bt-49.data.model &&
festlearn -d 1 -n 0.1 -t 50 train-raw-up.data train-raw-up-bt-50.data.model &&
festlearn -d 1 -n 0.1 -t 51 train-raw-up.data train-raw-up-bt-51.data.model &&
festlearn -d 1 -n 0.1 -t 52 train-raw-up.data train-raw-up-bt-52.data.model &&
festlearn -d 1 -n 0.1 -t 53 train-raw-up.data train-raw-up-bt-53.data.model &&
festlearn -d 1 -n 0.1 -t 54 train-raw-up.data train-raw-up-bt-54.data.model &&
festlearn -d 1 -n 0.1 -t 55 train-raw-up.data train-raw-up-bt-55.data.model &&
festlearn -d 1 -n 0.1 -t 56 train-raw-up.data train-raw-up-bt-56.data.model &&
festlearn -d 1 -n 0.1 -t 57 train-raw-up.data train-raw-up-bt-57.data.model &&
festlearn -d 1 -n 0.1 -t 58 train-raw-up.data train-raw-up-bt-58.data.model &&
festlearn -d 1 -n 0.1 -t 59 train-raw-up.data train-raw-up-bt-59.data.model &&
festlearn -d 1 -n 0.1 -t 60 train-raw-up.data train-raw-up-bt-60.data.model &&
festlearn -d 1 -n 0.1 -t 61 train-raw-up.data train-raw-up-bt-61.data.model &&
festlearn -d 1 -n 0.1 -t 62 train-raw-up.data train-raw-up-bt-62.data.model &&
festlearn -d 1 -n 0.1 -t 63 train-raw-up.data train-raw-up-bt-63.data.model &&
festlearn -d 1 -n 0.1 -t 64 train-raw-up.data train-raw-up-bt-64.data.model &&
festlearn -d 1 -n 0.1 -t 65 train-raw-up.data train-raw-up-bt-65.data.model &&
festlearn -d 1 -n 0.1 -t 66 train-raw-up.data train-raw-up-bt-66.data.model &&
festlearn -d 1 -n 0.1 -t 67 train-raw-up.data train-raw-up-bt-67.data.model &&
festlearn -d 1 -n 0.1 -t 68 train-raw-up.data train-raw-up-bt-68.data.model &&
festlearn -d 1 -n 0.1 -t 69 train-raw-up.data train-raw-up-bt-69.data.model &&
festlearn -d 1 -n 0.1 -t 70 train-raw-up.data train-raw-up-bt-70.data.model &&
festlearn -d 1 -n 0.1 -t 71 train-raw-up.data train-raw-up-bt-71.data.model &&
festlearn -d 1 -n 0.1 -t 72 train-raw-up.data train-raw-up-bt-72.data.model &&
festlearn -d 1 -n 0.1 -t 73 train-raw-up.data train-raw-up-bt-73.data.model &&
festlearn -d 1 -n 0.1 -t 74 train-raw-up.data train-raw-up-bt-74.data.model &&
festlearn -d 1 -n 0.1 -t 75 train-raw-up.data train-raw-up-bt-75.data.model &&
festlearn -d 1 -n 0.1 -t 76 train-raw-up.data train-raw-up-bt-76.data.model &&
festlearn -d 1 -n 0.1 -t 77 train-raw-up.data train-raw-up-bt-77.data.model &&
festlearn -d 1 -n 0.1 -t 78 train-raw-up.data train-raw-up-bt-78.data.model &&
festlearn -d 1 -n 0.1 -t 79 train-raw-up.data train-raw-up-bt-79.data.model &&
festlearn -d 1 -n 0.1 -t 80 train-raw-up.data train-raw-up-bt-80.data.model &&
festlearn -d 1 -n 0.1 -t 81 train-raw-up.data train-raw-up-bt-81.data.model &&
festlearn -d 1 -n 0.1 -t 82 train-raw-up.data train-raw-up-bt-82.data.model &&
festlearn -d 1 -n 0.1 -t 83 train-raw-up.data train-raw-up-bt-83.data.model &&
festlearn -d 1 -n 0.1 -t 84 train-raw-up.data train-raw-up-bt-84.data.model &&
festlearn -d 1 -n 0.1 -t 85 train-raw-up.data train-raw-up-bt-85.data.model &&
festlearn -d 1 -n 0.1 -t 86 train-raw-up.data train-raw-up-bt-86.data.model &&
festlearn -d 1 -n 0.1 -t 87 train-raw-up.data train-raw-up-bt-87.data.model &&
festlearn -d 1 -n 0.1 -t 88 train-raw-up.data train-raw-up-bt-88.data.model &&
festlearn -d 1 -n 0.1 -t 89 train-raw-up.data train-raw-up-bt-89.data.model &&
festlearn -d 1 -n 0.1 -t 90 train-raw-up.data train-raw-up-bt-90.data.model &&
festlearn -d 1 -n 0.1 -t 91 train-raw-up.data train-raw-up-bt-91.data.model &&
festlearn -d 1 -n 0.1 -t 92 train-raw-up.data train-raw-up-bt-92.data.model &&
festlearn -d 1 -n 0.1 -t 93 train-raw-up.data train-raw-up-bt-93.data.model &&
festlearn -d 1 -n 0.1 -t 94 train-raw-up.data train-raw-up-bt-94.data.model &&
festlearn -d 1 -n 0.1 -t 95 train-raw-up.data train-raw-up-bt-95.data.model &&
festlearn -d 1 -n 0.1 -t 96 train-raw-up.data train-raw-up-bt-96.data.model &&
festlearn -d 1 -n 0.1 -t 97 train-raw-up.data train-raw-up-bt-97.data.model &&
festlearn -d 1 -n 0.1 -t 98 train-raw-up.data train-raw-up-bt-98.data.model &&
festlearn -d 1 -n 0.1 -t 99 train-raw-up.data train-raw-up-bt-99.data.model &&
festlearn -d 1 -n 0.1 -t 100 train-raw-up.data train-raw-up-bt-100.data.model &&
festlearn -d 1 -n 0.1 -t 101 train-raw-up.data train-raw-up-bt-101.data.model &&
festlearn -d 1 -n 0.1 -t 102 train-raw-up.data train-raw-up-bt-102.data.model &&
festlearn -d 1 -n 0.1 -t 103 train-raw-up.data train-raw-up-bt-103.data.model &&
festlearn -d 1 -n 0.1 -t 104 train-raw-up.data train-raw-up-bt-104.data.model &&
festlearn -d 1 -n 0.1 -t 105 train-raw-up.data train-raw-up-bt-105.data.model &&
festlearn -d 1 -n 0.1 -t 106 train-raw-up.data train-raw-up-bt-106.data.model &&
festlearn -d 1 -n 0.1 -t 107 train-raw-up.data train-raw-up-bt-107.data.model &&
festlearn -d 1 -n 0.1 -t 108 train-raw-up.data train-raw-up-bt-108.data.model &&
festlearn -d 1 -n 0.1 -t 109 train-raw-up.data train-raw-up-bt-109.data.model &&
festlearn -d 1 -n 0.1 -t 110 train-raw-up.data train-raw-up-bt-110.data.model &&
festlearn -d 1 -n 0.1 -t 111 train-raw-up.data train-raw-up-bt-111.data.model &&
festlearn -d 1 -n 0.1 -t 112 train-raw-up.data train-raw-up-bt-112.data.model &&
festlearn -d 1 -n 0.1 -t 113 train-raw-up.data train-raw-up-bt-113.data.model &&
festlearn -d 1 -n 0.1 -t 114 train-raw-up.data train-raw-up-bt-114.data.model &&
festlearn -d 1 -n 0.1 -t 115 train-raw-up.data train-raw-up-bt-115.data.model &&
festlearn -d 1 -n 0.1 -t 116 train-raw-up.data train-raw-up-bt-116.data.model &&
festlearn -d 1 -n 0.1 -t 117 train-raw-up.data train-raw-up-bt-117.data.model &&
festlearn -d 1 -n 0.1 -t 118 train-raw-up.data train-raw-up-bt-118.data.model &&
festlearn -d 1 -n 0.1 -t 119 train-raw-up.data train-raw-up-bt-119.data.model &&
festlearn -d 1 -n 0.1 -t 120 train-raw-up.data train-raw-up-bt-120.data.model &&
festlearn -d 1 -n 0.1 -t 121 train-raw-up.data train-raw-up-bt-121.data.model &&
festlearn -d 1 -n 0.1 -t 122 train-raw-up.data train-raw-up-bt-122.data.model &&
festlearn -d 1 -n 0.1 -t 123 train-raw-up.data train-raw-up-bt-123.data.model &&
festlearn -d 1 -n 0.1 -t 124 train-raw-up.data train-raw-up-bt-124.data.model &&
festlearn -d 1 -n 0.1 -t 125 train-raw-up.data train-raw-up-bt-125.data.model &&
festlearn -d 1 -n 0.1 -t 126 train-raw-up.data train-raw-up-bt-126.data.model &&
festlearn -d 1 -n 0.1 -t 127 train-raw-up.data train-raw-up-bt-127.data.model &&
festlearn -d 1 -n 0.1 -t 128 train-raw-up.data train-raw-up-bt-128.data.model
