(TeX-add-style-hook "Reference"
 (lambda ()
    (LaTeX-add-bibitems
     "Ref:CustomerRelationshipManagement"
     "Ref:KDDCup2009"
     "Ref:WinningtheKDDCupIBMResearch"
     "Ref:AnalysisOfTheKDDCup2009"
     "Ref:ACombinationOfBoostingAndBaggingForKDD"
     "Ref:FeaturePartitioningAndBoosting"
     "Ref:ProceedingsOfKddCup2009"
     "Ref:EnsembleMethodsInMachineLearning"
     "Ref:DataMiningConceptsandTechniques"
     "Ref:EnsembleSelectionFromLibraryOfModels"
     "Ref:AnEmpiricalComparisonofVotingClassification"
     "Ref:AnEfficientVotingAlgorithmForFindingBiclusters"
     "Ref:AnEnsembleOfThreeClassifiersForKDD2009"
     "Ref:LargeLinearClassificationWhen"
     "Ref:ComparingBoostingandBaggingWithNoisyImbalancedData"
     "Ref:IncoprtatingBaggingIntoBoosting"
     "Ref:IntelligibleModelsForClassificationAndRegression"
     "Ref:DensityBasedLogicalRegression"
     "Ref:TradingRepresentabilityforScalability"
     "Ref:ANewClassifierBasedOnCompositeHypercubes"
     "Ref:DataMiningApplicationInCRM"
     "Ref:DataMiningStrategiesforCRM"
     "Ref:CRMBasedonDataMiningTechnique"
     "Ref:CostSensitiveDataPreprocessing"
     "Ref:ChallengesinKDDataMiningDatasets"
     "Ref:TowardsAnOptimalClassificationModel"
     "Ref:ApplicationOfDataMiningInCRM"
     "Ref:TargetingCustomers")))

