(TeX-add-style-hook "Report"
 (lambda ()
    (LaTeX-add-bibliographies
     "IEEEabrv"
     "Reference")
    (LaTeX-add-labels
     "sec:introduction"
     "sec:initial-plan"
     "fig:memory-consuming"
     "sec:preprocessing"
     "sec:base-classifiers"
     "sec:ensemble-selection"
     "sec:more-features-base"
     "sec:revised-proposal"
     "sec:matlab"
     "sec:weka"
     "sec:specific-packages"
     "fig:special-package-1"
     "sec:result-conclusion")
    (TeX-run-style-hooks
     "hyperref"
     "url"
     "fixltx2e"
     "subfig"
     "font=footnotesize"
     "caption=false"
     "eqparbox"
     "mdwtab"
     "mdwmath"
     "array"
     "algorithmic"
     ""
     "amsmath"
     "cmex10"
     "dvips"
     "graphicx"
     "pdftex"
     "cite"
     "noadjust"
     "latex2e"
     "IEEEtran10"
     "IEEEtran"
     "journal")))

